# Generated by Django 3.2.12 on 2022-02-21 22:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_customer', models.BooleanField(default=False)),
                ('is_technician', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'New'), ('O', 'Open'), ('X', 'Cancelled'), ('H', 'Hold'), ('W', 'Waiting'), ('C', 'Complete')], default='N', max_length=1)),
                ('level', models.CharField(choices=[('L', 'Low Urgency'), ('N', 'Normal Urgency'), ('C', 'Critical Urgency')], default='N', max_length=1)),
                ('requestor', models.CharField(max_length=80)),
                ('street1', models.CharField(max_length=80)),
                ('street2', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('customer_comment', models.TextField(blank=True, null=True)),
                ('dispatch_comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('cost', models.FloatField()),
                ('status', models.CharField(choices=[('W', 'At the warehouse'), ('U', 'Not Available'), ('D', 'Discontinued'), ('O', 'Order')], default='W', max_length=1)),
                ('leadtime', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=25)),
                ('payrate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tech.user')),
                ('phone', models.TextField(max_length=25)),
                ('street1', models.CharField(max_length=80)),
                ('street2', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=15)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tech.user')),
                ('phone', models.TextField(max_length=25)),
                ('street1', models.CharField(max_length=80)),
                ('street2', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=15)),
                ('comments', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.payrate')),
            ],
        ),
        migrations.CreateModel(
            name='TechHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.jobs')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartCategoryXref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.partcategory')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.part')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='TechUnavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.technician')),
            ],
        ),
        migrations.CreateModel(
            name='SkillTechXref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=5)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.skill')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.technician')),
            ],
        ),
        migrations.CreateModel(
            name='JobTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.jobs')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.technician')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcustomer', to='tech.customer'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobtechnician', to='tech.technician'),
        ),
        migrations.CreateModel(
            name='JobPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Dispatched'), ('T', 'With the Technician'), ('O', 'Ordered'), ('I', 'Installed'), ('C', 'Cancelled')], default='P', max_length=1)),
                ('eta', models.CharField(max_length=100)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tech.jobs')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.part')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.technician')),
            ],
        ),
    ]
