# Generated by Django 3.2.12 on 2022-02-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='technician',
            name='level',
        ),
        migrations.AddField(
            model_name='technician',
            name='level',
            field=models.ManyToManyField(to='tech.PayRate'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
