# Generated by Django 4.0.2 on 2022-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='appointment',
            field=models.DateTimeField(null=True),
        ),
    ]
