# Generated by Django 4.0.2 on 2022-02-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_job_created_at_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpart',
            name='cost',
            field=models.FloatField(default=25, verbose_name=models.FloatField(verbose_name='Cost $')),
            preserve_default=False,
        ),
    ]
