# Generated by Django 3.2.12 on 2022-02-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20220223_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltechxref',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skilltechxref',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='level',
        ),
        migrations.AddField(
            model_name='technician',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech.payrate'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PartCategoryXref',
        ),
        migrations.DeleteModel(
            name='SkillTechXref',
        ),
    ]
