# Generated by Django 4.0.2 on 2022-02-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_job_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtime',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='parts',
            field=models.ManyToManyField(to='tech.Part'),
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.ManyToManyField(to='tech.JobTime'),
        ),
        migrations.AlterField(
            model_name='job',
            name='appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JobPart',
        ),
    ]
