# Generated by Django 4.0.2 on 2022-02-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_remove_jobtime_job_job_parts_job_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='job',
            name='time',
        ),
        migrations.AddField(
            model_name='jobtime',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech.job'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Dispatched'), ('T', 'With the Technician'), ('O', 'Ordered'), ('I', 'Installed'), ('C', 'Cancelled')], default='P', max_length=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.job')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.part')),
            ],
        ),
    ]
