# Generated by Django 3.2.12 on 2022-02-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_auto_20220223_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='city',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='state',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='zip',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Lincoln', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='402-555-1212', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='NE', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street1',
            field=models.CharField(default='123 Main Street', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.CharField(default=68516, max_length=15),
            preserve_default=False,
        ),
    ]
