# Generated by Django 3.2.12 on 2022-02-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_alter_workingday_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='comments',
        ),
    ]
