# Generated by Django 3.2.12 on 2022-02-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_remove_technician_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='lunchend',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='lunchstart',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='startime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='tech.WorkingDay'),
        ),
    ]
