# Generated by Django 3.2.12 on 2022-02-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_auto_20220223_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='endtime',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='lunchend',
            field=models.TimeField(blank=True, default='13:00', null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='lunchstart',
            field=models.TimeField(blank=True, default='12:00', null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='startime',
            field=models.TimeField(blank=True, default='08:00', null=True),
        ),
    ]
