# Generated by Django 3.2.12 on 2022-02-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_auto_20220223_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='lunchend',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='lunchstart',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='startime',
        ),
    ]
