# Generated by Django 3.2.12 on 2022-02-23 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0010_auto_20220223_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_technician',
        ),
        migrations.AddField(
            model_name='technician',
            name='skills',
            field=models.ManyToManyField(to='tech.Skill', verbose_name='Technician Skills'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='days',
            field=models.ManyToManyField(to='tech.WorkingDay', verbose_name='Working Days'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.payrate', verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Related System User'),
        ),
        migrations.DeleteModel(
            name='TechUnavailable',
        ),
    ]
