# Generated by Django 4.0.2 on 2022-02-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0011_auto_20220223_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.TextField(choices=[('C', 'Customer'), ('T', 'Technician'), ('S', 'Staff')], default='T', max_length=10),
        ),
    ]
